In [1]:
## Dataset Reading
import pandas as pd
import numpy as np
df = pd.read_csv("processed_heart_disease_uci.csv")
df

,age,sex,trestbps,chol,fbs,thalch,exang,oldpeak,ca,target,cp_atypical angina,cp_non-anginal,cp_typical angina,restecg_normal,restecg_st-t abnormality,slope_flat,slope_upsloping,thal_normal,thal_reversable defect
0,63,1,145.0,233.0,1,150.0,0,2.3,0.0,0,0,0,1,0,0,0,0,0,0
1,67,1,160.0,286.0,0,108.0,1,1.5,3.0,1,0,0,0,0,0,1,0,1,0
2,67,1,120.0,229.0,0,129.0,1,2.6,2.0,1,0,0,0,0,0,1,0,0,1
3,37,1,130.0,250.0,0,187.0,0,3.5,0.0,0,0,1,0,1,0,0,0,1,0
4,41,0,130.0,204.0,0,172.0,0,1.4,0.0,0,1,0,0,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
915,54,0,127.0,333.0,1,154.0,0,0.0,0.0,1,0,0,0,0,1,1,0,1,0
916,62,1,130.0,139.0,0,140.0,0,0.5,0.0,0,0,0,1,0,1,1,0,1,0
917,55,1,122.0,223.0,1,100.0,0,0.0,0.0,1,0,0,0,0,1,1,0,0,0
918,58,1,130.0,385.0,1,140.0,0,0.5,0.0,0,0,0,0,0,0,1,0,1,0


In [2]:
from sklearn.model_selection import train_test_split
columns = df.columns
columns = columns.drop("target")

In [3]:
X = df[columns]
X.shape


(920, 18)

In [4]:
Y = df["target"]

In [5]:
X_train , X_test , y_train , y_test = train_test_split(X , Y , test_size = 0.2 , random_state= 42)

In [6]:
X_train.shape

(736, 18)

In [7]:
X_test.shape

(184, 18)

In [8]:
y_train.shape

(736,)

In [9]:
y_test.shape

(184,)

In [10]:
## Scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [11]:
X_train

array([[ 0.90241255,  0.50593744, -0.08394637, ..., -0.55223595,
         0.57525841, -0.49745113],
       [ 0.03477619,  0.50593744,  0.98777137, ..., -0.55223595,
         0.57525841, -0.49745113],
       [-0.29058745,  0.50593744, -0.08394637, ..., -0.55223595,
         0.57525841, -0.49745113],
       ...,
       [ 2.31232163,  0.50593744,  1.52363024, ..., -0.55223595,
        -1.73834919,  2.01024772],
       [-0.07367836, -1.97652894,  0.4519125 , ..., -0.55223595,
         0.57525841, -0.49745113],
       [ 0.36013982, -1.97652894, -0.19111814, ...,  1.81082019,
         0.57525841, -0.49745113]])

In [12]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
lr.fit(X_train , y_train)

LogisticRegression()

In [13]:
lr.intercept_

array([0.30643076])

In [14]:
lr.coef_

array([[ 0.12920252,  0.58584387,  0.04469635, -0.54002991,  0.14676556,
        -0.25890786,  0.44253125,  0.64076949,  0.53207828, -0.75784099,
        -0.58595447, -0.31810694,  0.0945814 ,  0.21799746,  0.25652135,
        -0.06444984, -0.23992276,  0.03505759]])

In [15]:
y_pred = lr.predict(X_test)
y_pred

array([0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 1])

In [16]:
from sklearn.metrics import confusion_matrix , precision_score , recall_score , f1_score , accuracy_score
confusion_matrix(y_pred , y_test)
confusion_matrix(y_test , y_pred)

array([[60, 15],
       [22, 87]])

In [17]:
precision_score(y_pred , y_test)*100

np.float64(79.81651376146789)

In [18]:
recall_score(y_pred , y_test)*100

np.float64(85.29411764705883)

In [19]:
accuracy_score(y_pred , y_test)*100

79.8913043478261

In [20]:
precision_score(y_pred , y_test , average=None)

array([0.8       , 0.79816514])

In [21]:
precision_score(y_pred , y_test , average=None).shape

(2,)

In [22]:
recall_score(y_pred , y_test, average=None)

array([0.73170732, 0.85294118])

In [23]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.73      0.80      0.76        75
           1       0.85      0.80      0.82       109

    accuracy                           0.80       184
   macro avg       0.79      0.80      0.79       184
weighted avg       0.80      0.80      0.80       184

