In [1]:
## Dataset Reading ## Voting Ensemble
import pandas as pd
import numpy as np
df = pd.read_csv("processed_data.csv")
df

,age,sex,trestbps,chol,fbs,thalch,exang,oldpeak,ca,target,cp_atypical angina,cp_non-anginal,cp_typical angina,restecg_normal,restecg_st-t abnormality,slope_flat,slope_upsloping,thal_normal,thal_reversable defect
0,63,1,145.0,233.0,1,150.0,0,2.3,0.0,0,0,0,1,0,0,0,0,0,0
1,67,1,160.0,286.0,0,108.0,1,1.5,3.0,1,0,0,0,0,0,1,0,1,0
2,67,1,120.0,229.0,0,129.0,1,2.6,2.0,1,0,0,0,0,0,1,0,0,1
3,37,1,130.0,250.0,0,187.0,0,3.5,0.0,0,0,1,0,1,0,0,0,1,0
4,41,0,130.0,204.0,0,172.0,0,1.4,0.0,0,1,0,0,0,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
915,54,0,127.0,333.0,1,154.0,0,0.0,0.0,1,0,0,0,0,1,1,0,1,0
916,62,1,130.0,139.0,0,140.0,0,0.5,0.0,0,0,0,1,0,1,1,0,1,0
917,55,1,122.0,223.0,1,100.0,0,0.0,0.0,1,0,0,0,0,1,1,0,0,0
918,58,1,130.0,385.0,1,140.0,0,0.5,0.0,0,0,0,0,0,0,1,0,1,0


In [2]:
from sklearn.model_selection import train_test_split
columns = df.columns
columns = columns.drop("target")
X = df[columns]
Y = df["target"]

In [3]:
X_train , X_test , y_train , y_test = train_test_split(X , Y , test_size = 0.2 , random_state= 42)

In [4]:
## Scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [43]:
from sklearn.ensemble import VotingClassifier 
from sklearn.linear_model import LogisticRegression 
from sklearn.tree import DecisionTreeClassifier 
lr = LogisticRegression() 
dt = DecisionTreeClassifier(
    max_depth=4,
    min_samples_split=10,
    min_samples_leaf=5,
    random_state=42
)

In [44]:
model = VotingClassifier( 
estimators=[('lr', lr), ('dt', dt)], 
voting='hard' 
) 
model.fit(X_train, y_train) 
pred = model.predict(X_test) 

In [45]:
pred

array([0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 1])

In [46]:
from sklearn.metrics import accuracy_score
accuracy_score(pred , y_test)

0.7608695652173914

In [47]:
from sklearn.metrics import classification_report

print(classification_report(y_test, pred))

              precision    recall  f1-score   support

           0       0.65      0.91      0.76        75
           1       0.91      0.66      0.77       109

    accuracy                           0.76       184
   macro avg       0.78      0.78      0.76       184
weighted avg       0.80      0.76      0.76       184



In [48]:
from sklearn.metrics import confusion_matrix 

confusion_matrix(y_test , pred)

array([[68,  7],
       [37, 72]])

In [49]:
model2 = VotingClassifier( 
estimators=[('lr', lr), ('dt', dt)], 
voting='soft' 
) 
model2.fit(X_train, y_train) 
pred2 = model.predict(X_test) 

In [50]:
from sklearn.metrics import accuracy_score
accuracy_score(pred2 , y_test)

0.7608695652173914

In [51]:
confusion_matrix(y_test , pred2)

array([[68,  7],
       [37, 72]])